// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB35VjXzbTGTSVpljGXbiSsFvArMXkDKk',
    appId: '1:532744094450:web:de14b8e5a18afb6d62c66b',
    messagingSenderId: '532744094450',
    projectId: 'itachi-wtw',
    authDomain: 'itachi-wtw.firebaseapp.com',
    storageBucket: 'itachi-wtw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-eauH_NCLaJ7R2Opv5kEHLcaPGrxViU',
    appId: '1:532744094450:android:e51873e9ae39b8e662c66b',
    messagingSenderId: '532744094450',
    projectId: 'itachi-wtw',
    storageBucket: 'itachi-wtw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3fxIJLjvmw06q1lQ2NNEp_vEvWQBLfQM',
    appId: '1:532744094450:ios:8bfc07e8f76fe58162c66b',
    messagingSenderId: '532744094450',
    projectId: 'itachi-wtw',
    storageBucket: 'itachi-wtw.firebasestorage.app',
    iosBundleId: 'com.example.wtw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3fxIJLjvmw06q1lQ2NNEp_vEvWQBLfQM',
    appId: '1:532744094450:ios:8bfc07e8f76fe58162c66b',
    messagingSenderId: '532744094450',
    projectId: 'itachi-wtw',
    storageBucket: 'itachi-wtw.firebasestorage.app',
    iosBundleId: 'com.example.wtw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB35VjXzbTGTSVpljGXbiSsFvArMXkDKk',
    appId: '1:532744094450:web:e7117b9a5943203562c66b',
    messagingSenderId: '532744094450',
    projectId: 'itachi-wtw',
    authDomain: 'itachi-wtw.firebaseapp.com',
    storageBucket: 'itachi-wtw.firebasestorage.app',
  );
}
